export { default as logo} from "./logo.png";
export { default as film } from "./film.png";
export { default as heart } from "./heart.png";
export { default as log_out } from "./log-out.png";
export { default as message_circle } from "./message-circle.png";
export { default as sliders } from "./sliders.png";
export { default as trending_up } from "./trending-up.png";
export { default as users } from "./users.png";
export { default as calender } from "./calendar.png";
export { default as search } from "./search.png";
export { default as bell } from "./bell.png";
export { default as avatar } from "./Group98.png";
export { default as white } from "./Frame9.png";
export { default as purple } from "./Frame7.png";
export { default as movie1 } from "./movie1.png";
export { default as movie2 } from "./movie2.png";
export { default as movie3} from "./movie3.png";
export { default as movie4 } from "./movie4.png";
export { default as movie5 } from "./movie5.png";
export { default as movie6 } from "./movie6.png";
export { default as movie7 } from "./movie7.png";
export { default as star } from "./star.png";